language: go

script:
    # staticcheck only works for two newest go versions
    - if [[ "$(go version)" =~ go1.1[12] ]]; then go get honnef.co/go/tools/cmd/staticcheck && staticcheck ./... && echo "staticcheck complete"; fi
    - go vet ./...
    - go test ./...

go:
  - 1.11.x
  - 1.12.x

sudo: false
